DELETE http://localhost:3003/api/blogs/64676964b8c35d17ab586cdb
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NjE3YTdjOTNjOWI1YTRlOTk1NGE4NCIsImlhdCI6MTY4NDIzOTM5MH0.x0fo1G7J0OyMAEwCKZVC4Pd71NvSQxpVNhDn-tDPrik
